name: Release new version

on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.json

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
    
      - name: Restore dependencies
        working-directory: SignalTrader
        run: dotnet restore "SignalTrader.csproj"
    
      - name: Build
        working-directory: SignalTrader
        run: dotnet build "SignalTrader.csproj" -c Release --no-restore
    
      - name: Test
        working-directory: SignalTraderTests
        run: dotnet test "SignalTraderTests.csproj" -c Release /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

      - name: Publish coverage report to coveralls.io   
        uses: coverallsapp/github-action@master   
        with:
          github-token: ${{ secrets.PAT }} 
          path-to-lcov: SignalTraderTests/TestResults/coverage.info 

  release:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Perform semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: npx -p @semantic-release/git -p @semantic-release/changelog -p @semantic-release/exec -p @google/semantic-release-replace-plugin -p @semantic-release-plus/docker -p conventional-changelog-conventionalcommits semantic-release
